#!/usr/bin/env bash
# Rasterise the station + launcher artwork into per-screen-family drawable
# folders (resources-<deviceFamily>/drawables/).
#
# Connect IQ resolves drawables by resource qualifier: a folder named
# resources-<deviceFamily> (e.g. resources-round-390x390) is auto-merged for
# EVERY device in that family, so one folder covers a whole screen class — no
# per-device folders and no monkey.jungle wiring.
#
# Icons are drawn at native pixel size and centred in each strip tile
# (StripView.drawBitmap), so the icon size scales with the screen. The formula
# below (0.133*minDim + 12) passes through the two hand-tuned originals:
# 44px @ 240px and 64px @ 390px.
#
# The launcher icon is the ONLY size-sensitive asset — it's declared in the
# manifest, so Connect IQ warns (and scales) when the PNG size differs from the
# device's expected launcher size. A family can contain devices that disagree on
# that size, so one PNG can't satisfy all of them. Each family's launcher is set
# to the MOST COMMON size in the family (fewest devices scaled), except the two
# primary side-load targets are pinned EXACT so `./build.sh` stays 0-warning:
# round-390x390 = 56 (vivoactive5), round-240x240 = 40 (fr745). Benign
# "will be scaled" notes on other devices in `./build.sh fleet` are expected.
#
# Uses rsvg-convert — ImageMagick's built-in SVG renderer drops the strokes
# these icons are mostly made of. Re-run whenever icons/*.svg change or a new
# screen family is added to manifest.xml.
set -euo pipefail
cd "$(dirname "$0")/.."

command -v rsvg-convert >/dev/null || { echo "rsvg-convert not found"; exit 1; }

STATIONS=(finnish_sauna fire_ice_room heated_loungers hot_tub hydro_pool ice_cave \
          indoor_cold_plunge outdoor_cold_plunge outdoor_lounger salt_sauna steam_room)

# family                icon launcher   (launcher = most common in family;
#                                         round-390/240 pinned to va5/fr745)
FAMILIES=(
  "rectangle-240x240     44  36"
  "rectangle-320x360     55  40"
  "rectangle-448x486     72  65"
  "round-208x208         40  35"
  "round-218x218         41  30"
  "round-240x240         44  40"
  "round-260x260         47  40"
  "round-280x280         49  40"
  "round-360x360         60  60"
  "round-390x390         64  56"
  "round-416x416         67  60"
  "round-454x454         72  65"
  "semioctagon-163x156   33  54"
  "semioctagon-166x166   34  52"
  "semioctagon-176x176   35  62"
)

for row in "${FAMILIES[@]}"; do
  read -r fam icon launcher <<<"$row"
  dir="resources-$fam/drawables"
  mkdir -p "$dir"
  echo ">> $fam  icons=${icon}px launcher=${launcher}px -> $dir"

  rsvg-convert -w "$launcher" -h "$launcher" icons/app_icon.svg -o "$dir/launcher_icon.png"
  for s in "${STATIONS[@]}"; do
    rsvg-convert -w "$icon" -h "$icon" "icons/$s.svg" -o "$dir/st_$s.png"
  done

  {
    echo '<drawables>'
    echo "    <!-- Generated by tools/rasterise-icons.sh for the $fam screen family."
    echo "         Launcher ${launcher}px; station icons ${icon}px. Do not hand-edit. -->"
    echo '    <bitmap id="LauncherIcon" filename="launcher_icon.png" />'
    for s in "${STATIONS[@]}"; do
      echo "    <bitmap id=\"st_$s\" filename=\"st_$s.png\" />"
    done
    echo '</drawables>'
  } > "$dir/drawables.xml"
done

echo "done: $(ls -d resources-round-* resources-rectangle-* resources-semioctagon-* | wc -l) family folders"
