import { defineConfig } from 'drizzle-kit'

// `drizzle-kit generate` diffs the schema files and writes SQL migrations to
// ./migrations. Migrations are applied with `wrangler d1 migrations apply`
// (see README), never `drizzle-kit migrate`.
//
// auth-schema.ts is better-auth's own tables, generated by its CLI. It goes
// through the same migration path as everything else so wrangler stays the only
// thing that touches the database.
export default defineConfig({
    schema: ['./src/db/schema.ts', './src/db/auth-schema.ts'],
    out: './migrations',
    dialect: 'sqlite',
})
